# version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  python:
    image: python:3.13
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    command: tail -f /dev/null

volumes:
  postgres_data: