# Generated by Django 5.1.3 on 2024-11-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesession',
            old_name='name',
            new_name='session',
        ),
        migrations.RemoveField(
            model_name='servicesession',
            name='description',
        ),
    ]
