# Generated by Django 5.0.8 on 2024-11-18 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_workerprofile_user_delete_userprofile_and_more'),
        ('services', '0004_serviceorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('looking_for_worker', 'Looking for Nearby Worker'), ('worker_assigned', 'Waiting for Worker'), ('in_progress', 'Service in Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='looking_for_worker', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.subcategory')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.worker')),
            ],
        ),
    ]
