# Generated by Django 5.1.1 on 2024-12-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_workerserviceorder_worker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='session',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='ServiceOrder',
        ),
        migrations.RemoveField(
            model_name='servicesession',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='workerserviceorder',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='workerservice',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workerservice',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='workerserviceorder',
            name='assigned_worker',
        ),
        migrations.RemoveField(
            model_name='workerserviceorder',
            name='workers',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
        migrations.DeleteModel(
            name='ServiceSession',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='WorkerService',
        ),
        migrations.DeleteModel(
            name='WorkerServiceOrder',
        ),
    ]
