# Generated by Django 5.1.3 on 2024-11-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_options_alter_worker_options_and_more'),
        ('main', '0002_userprofile_workerprofile'),
    ]

    operations = [
    ]
