# Generated by Django 5.1.3 on 2024-11-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merge_20241117_1538'),
        ('main', '0004_alter_workerprofile_image_url'),
    ]

    operations = [
    ]
