# Generated by Django 5.1.3 on 2024-11-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20241117_1704'),
        ('main', '0005_merge_20241118_0059'),
    ]

    operations = [
    ]
