# Generated by Django 5.1.3 on 2024-11-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_workerprofile_user_delete_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mypay_balance',
            field=models.IntegerField(default=0),
        ),
    ]
