# Generated by Django 5.1.1 on 2024-12-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_transfertransaction'),
        ('services', '0007_remove_booking_session_remove_booking_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promo',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transfertransaction',
            name='transaction_ptr',
        ),
        migrations.RemoveField(
            model_name='transfertransaction',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
        migrations.DeleteModel(
            name='TransactionCategory',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransferTransaction',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
